import Header from "@/components/Nav/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/AuthProvider/authProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shoe Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" translate="no">
      <AuthProvider>
        <body className={inter.className}>
          <Header />
          <Toaster position="bottom-left"/>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
